substitutions:
  name: jbd-bms
  device_description: "Monitor and control a Xiaoxiang Battery Management System (JBD-BMS UP) via RS485"
  external_components_source: github://smaksimowicz/esphome-jbd-bms@main
  tx_pin: GPIO17
  rx_pin: GPIO16
  rx_timeout: 150ms

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "smaksimowicz.esphome-jbd-bms"
    version: 1.0.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: "Mak"
  password: "0123456789"

ota:
  password: "a00db62ae10969229cdc443b672aaea4"

logger:
  level: ERROR

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
#mqtt:
#  broker: !secret mqtt_host
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  id: mqtt_client

api:
 encryption:
    key: "0BQx4CfwdfLngyNtibfTIcwlP4TkN69RfOlSEqrtXfs="

uart:
  - id: uart_0
    baud_rate: 9600
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

jbd_bms:
  - id: bms0   
    update_interval: 2s
    rx_timeout: ${rx_timeout}
    modbus_id: 0
  - id: bms1   
    update_interval: 2s
    rx_timeout: ${rx_timeout}
    modbus_id: 1
  - id: bms2   
    update_interval: 2s
    rx_timeout: ${rx_timeout}
    modbus_id: 2

binary_sensor:
  - platform: jbd_bms
    jbd_bms_id: bms0
    balancing:
      name: "${name} bms0 balancing"
    charging:
      name: "${name} bms0 charging"
    discharging:
      name: "${name} bms0 discharging"
    online_status:
      name: "${name} bms0 online status"
  - platform: jbd_bms
    jbd_bms_id: bms1
    balancing:
      name: "${name} bms1 balancing"
    charging:
      name: "${name} bms1 charging"
    discharging:
      name: "${name} bms1 discharging"
    online_status:
      name: "${name} bms1 online status"
  - platform: jbd_bms
    jbd_bms_id: bms2
    balancing:
      name: "${name} bms2 balancing"
    charging:
      name: "${name} bms2 charging"
    discharging:
      name: "${name} bms2 discharging"
    online_status:
      name: "${name} bms2 online status"
sensor:

  - platform: jbd_bms
    jbd_bms_id: bms0
    battery_strings:
      name: "${name} bms0 battery strings"
    current:
      name: "${name} bms0 current"
    power:
      name: "${name} bms0 power"
      id: jbd_bms_bms0_power
    charging_power:
      name: "${name} bms0 charging power"
    discharging_power:
      name: "${name} bms0 discharging power"
    state_of_charge:
      name: "${name} bms0 state of charge"
    nominal_capacity:
      name: "${name} bms0 nominal capacity"
    charging_cycles:
      name: "${name} bms0 charging cycles"
    capacity_remaining:
      name: "${name} bms0 capacity remaining"
    battery_cycle_capacity:
      name: "${name} bms0 battery cycle capacity"
    total_voltage:
      name: "${name} bms0 total voltage"
    average_cell_voltage:
      name: "${name} bms0 average cell voltage"
    delta_cell_voltage:
      name: "${name} bms0 delta cell voltage"
    min_cell_voltage:
      name: "${name} bms0 min cell voltage"
    max_cell_voltage:
      name: "${name} bms0 max cell voltage"
    min_voltage_cell:
      name: "${name} bms0 min voltage cell"
    max_voltage_cell:
      name: "${name} bms0 max voltage cell"
    temperature_1:
      name: "${name} bms0 temperature 1"
    temperature_2:
      name: "${name} bms0 temperature 2"
    temperature_3:
      name: "${name} bms0 temperature 3"
    temperature_4:
      name: "${name} bms0 temperature 4"
    temperature_ambient:
      name: "${name} bms0 temperature ambient"
    temperature_fet:
      name: "${name} bms0 temperature fet"
    cell_voltage_1:
      name: "${name} bms0 cell voltage 1"
    cell_voltage_2:
      name: "${name} bms0 cell voltage 2"
    cell_voltage_3:
      name: "${name} bms0 cell voltage 3"
    cell_voltage_4:
      name: "${name} bms0 cell voltage 4"
    cell_voltage_5:
      name: "${name} bms0 cell voltage 5"
    cell_voltage_6:
      name: "${name} bms0 cell voltage 6"
    cell_voltage_7:
      name: "${name} bms0 cell voltage 7"
    cell_voltage_8:
      name: "${name} bms0 cell voltage 8"
    cell_voltage_9:
      name: "${name} bms0 cell voltage 9"
    cell_voltage_10:
      name: "${name} bms0 cell voltage 10"
    cell_voltage_11:
      name: "${name} bms0 cell voltage 11"
    cell_voltage_12:
      name: "${name} bms0 cell voltage 12"
    cell_voltage_13:
      name: "${name} bms0 cell voltage 13"
    cell_voltage_14:
      name: "${name} bms0 cell voltage 14"
    cell_voltage_15:
      name: "${name} bms0 cell voltage 15"
    cell_voltage_16:
      name: "${name} bms0 cell voltage 16"
    operation_status_bitmask:
      name: "${name} bms0 operation status bitmask"
    errors_bitmask:
      name: "${name} bms0 errors bitmask"
    alarm_bitmask:
        name: "${name} bms0 alarm bitmask"
    balancer_status_bitmask:
      name: "${name} bms0 balancer status bitmask"
    software_version:
      name: "${name} bms0 software version"
  - platform: jbd_bms
    jbd_bms_id: bms1
    battery_strings:
      name: "${name} bms1 battery strings"
    current:
      name: "${name} bms1 current"
    power:
      name: "${name} bms1 power"
      id: jbd_bms_bms1_power
    charging_power:
      name: "${name} bms1 charging power"
    discharging_power:
      name: "${name} bms1 discharging power"
    state_of_charge:
      name: "${name} bms1 state of charge"
    nominal_capacity:
      name: "${name} bms1 nominal capacity"
    charging_cycles:
      name: "${name} bms1 charging cycles"
    capacity_remaining:
      name: "${name} bms1 capacity remaining"
    battery_cycle_capacity:
      name: "${name} bms1 battery cycle capacity"
    total_voltage:
      name: "${name} bms1 total voltage"
    average_cell_voltage:
      name: "${name} bms1 average cell voltage"
    delta_cell_voltage:
      name: "${name} bms1 delta cell voltage"
    min_cell_voltage:
      name: "${name} bms1 min cell voltage"
    max_cell_voltage:
      name: "${name} bms1 max cell voltage"
    min_voltage_cell:
      name: "${name} bms1 min voltage cell"
    max_voltage_cell:
      name: "${name} bms1 max voltage cell"
    temperature_1:
      name: "${name} bms1 temperature 1"
    temperature_2:
      name: "${name} bms1 temperature 2"
    temperature_3:
      name: "${name} bms1 temperature 3"
    temperature_4:
      name: "${name} bms1 temperature 4"
    temperature_ambient:
      name: "${name} bms1 temperature ambient"
    temperature_fet:
      name: "${name} bms1 temperature fet"
    cell_voltage_1:
      name: "${name} bms1 cell voltage 1"
    cell_voltage_2:
      name: "${name} bms1 cell voltage 2"
    cell_voltage_3:
      name: "${name} bms1 cell voltage 3"
    cell_voltage_4:
      name: "${name} bms1 cell voltage 4"
    cell_voltage_5:
      name: "${name} bms1 cell voltage 5"
    cell_voltage_6:
      name: "${name} bms1 cell voltage 6"
    cell_voltage_7:
      name: "${name} bms1 cell voltage 7"
    cell_voltage_8:
      name: "${name} bms1 cell voltage 8"
    cell_voltage_9:
      name: "${name} bms1 cell voltage 9"
    cell_voltage_10:
      name: "${name} bms1 cell voltage 10"
    cell_voltage_11:
      name: "${name} bms1 cell voltage 11"
    cell_voltage_12:
      name: "${name} bms1 cell voltage 12"
    cell_voltage_13:
      name: "${name} bms1 cell voltage 13"
    cell_voltage_14:
      name: "${name} bms1 cell voltage 14"
    cell_voltage_15:
      name: "${name} bms1 cell voltage 15"
    cell_voltage_16:
      name: "${name} bms1 cell voltage 16"
    operation_status_bitmask:
      name: "${name} bms1 operation status bitmask"
    errors_bitmask:
      name: "${name} bms1 errors bitmask"
    alarm_bitmask:
        name: "${name} bms1 alarm bitmask"
    balancer_status_bitmask:
      name: "${name} bms1 balancer status bitmask"
    software_version:
      name: "${name} bms1 software version"
  - platform: jbd_bms
    jbd_bms_id: bms2
    battery_strings:
      name: "${name} bms2 battery strings"
    current:
      name: "${name} bms2 current"
    power:
      name: "${name} bms2 power"
      id: jbd_bms_bms2_power
    charging_power:
      name: "${name} bms2 charging power"
    discharging_power:
      name: "${name} bms2 discharging power"
    state_of_charge:
      name: "${name} bms2 state of charge"
    nominal_capacity:
      name: "${name} bms2 nominal capacity"
    charging_cycles:
      name: "${name} bms2 charging cycles"
    capacity_remaining:
      name: "${name} bms2 capacity remaining"
    battery_cycle_capacity:
      name: "${name} bms2 battery cycle capacity"
    total_voltage:
      name: "${name} bms2 total voltage"
    average_cell_voltage:
      name: "${name} bms2 average cell voltage"
    delta_cell_voltage:
      name: "${name} bms2 delta cell voltage"
    min_cell_voltage:
      name: "${name} bms2 min cell voltage"
    max_cell_voltage:
      name: "${name} bms2 max cell voltage"
    min_voltage_cell:
      name: "${name} bms2 min voltage cell"
    max_voltage_cell:
      name: "${name} bms2 max voltage cell"
    temperature_1:
      name: "${name} bms2 temperature 1"
    temperature_2:
      name: "${name} bms2 temperature 2"
    temperature_3:
      name: "${name} bms2 temperature 3"
    temperature_4:
      name: "${name} bms2 temperature 4"
    temperature_ambient:
      name: "${name} bms2 temperature ambient"
    temperature_fet:
      name: "${name} bms2 temperature fet"
    cell_voltage_1:
      name: "${name} bms2 cell voltage 1"
    cell_voltage_2:
      name: "${name} bms2 cell voltage 2"
    cell_voltage_3:
      name: "${name} bms2 cell voltage 3"
    cell_voltage_4:
      name: "${name} bms2 cell voltage 4"
    cell_voltage_5:
      name: "${name} bms2 cell voltage 5"
    cell_voltage_6:
      name: "${name} bms2 cell voltage 6"
    cell_voltage_7:
      name: "${name} bms2 cell voltage 7"
    cell_voltage_8:
      name: "${name} bms2 cell voltage 8"
    cell_voltage_9:
      name: "${name} bms2 cell voltage 9"
    cell_voltage_10:
      name: "${name} bms2 cell voltage 10"
    cell_voltage_11:
      name: "${name} bms2 cell voltage 11"
    cell_voltage_12:
      name: "${name} bms2 cell voltage 12"
    cell_voltage_13:
      name: "${name} bms2 cell voltage 13"
    cell_voltage_14:
      name: "${name} bms2 cell voltage 14"
    cell_voltage_15:
      name: "${name} bms2 cell voltage 15"
    cell_voltage_16:
      name: "${name} bms2 cell voltage 16"
    operation_status_bitmask:
      name: "${name} bms2 operation status bitmask"
    errors_bitmask:
      name: "${name} bms2 errors bitmask"
    alarm_bitmask:
        name: "${name} bms2 alarm bitmask"
    balancer_status_bitmask:
      name: "${name} bms2 balancer status bitmask"
    software_version:
      name: "${name} bms2 software version"
  
  - platform: template
    name:  "${name} bms0 positive power"
    unit_of_measurement: "W"
    lambda: |-
      if (id(jbd_bms_bms0_power).state > 0) {
        return id(jbd_bms_bms0_power).state;
      } else {
        return -id(jbd_bms_bms0_power).state;
      }
    update_interval: 2s
  - platform: template
    name:  "${name} bms1 positive power"
    unit_of_measurement: "W"
    lambda: |-
      if (id(jbd_bms_bms1_power).state > 0) {
        return id(jbd_bms_bms1_power).state;
      } else {
        return -id(jbd_bms_bms1_power).state;
      }
    update_interval: 2s
  - platform: template
    name:  "${name} bms2 positive power"
    unit_of_measurement: "W" 
    lambda: |-
      if (id(jbd_bms_bms2_power).state > 0) {
        return id(jbd_bms_bms2_power).state;
      } else {
        return -id(jbd_bms_bms2_power).state;
      }
    update_interval: 2s

text_sensor:
  - platform: jbd_bms
    jbd_bms_id: bms0
    errors:
      name: "${name} bms0 errors"
    alarms:
      name: "${name} bms0 alarms"
    operation_status:
      name: "${name} bms0 operation status"
    device_model:
      name: "${name} bms0 device model"
  - platform: jbd_bms
    jbd_bms_id: bms1
    errors:
      name: "${name} bms1 errors"
    alarms:
      name: "${name} bms1 alarms"
    operation_status:
      name: "${name} bms1 operation status"
    device_model:
      name: "${name} bms1 device model"
  - platform: jbd_bms
    jbd_bms_id: bms2
    errors:
      name: "${name} bms2 errors"
    alarms:
      name: "${name} bms2 alarms"
    operation_status:
      name: "${name} bms2 operation status"
    device_model:
      name: "${name} bms2 device model"

switch:
  - platform: gpio
    pin:
     number: GPIO19
     inverted: true
    name: "Bms0 enable external balancer"
    id: bms0_external_balancer_switch
  - platform: gpio
    pin:
     number: GPIO18
     inverted: true
    name: "Bms1 enable external balancer" 
    id: bms1_external_balancer_switch
  - platform: gpio
    pin: 
     number: GPIO5
     inverted: true
    name: "Bms2 enable external balancer"
    id: bms2_external_balancer_switch
  - platform: jbd_bms
    jbd_bms_id: bms0
    charging:
      name: "${name} bms0 charging"
    discharging:
      name: "${name} bms0 discharging"
    balancer:
      name: "${name} bms0 balancer"
  - platform: jbd_bms
    jbd_bms_id: bms1
    charging:
      name: "${name} bms1 charging"
    discharging:
      name: "${name} bms1 discharging"
    balancer:
      name: "${name} bms1 balancer"
  - platform: jbd_bms
    jbd_bms_id: bms2
    charging:
      name: "${name} bms2 charging"
    discharging:
      name: "${name} bms2 discharging"
    balancer:
      name: "${name} bms2 balancer"

      
      